[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lending = "97YYarShCWE9y4rmJasvoSxeMCoX7c4ncJEjwW3nruax"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
